### ISSUE TITLE
No es necesario este import

### ISSUE THREAD

**Issue by gaal1le0** [keikeka/Simple-Counter-with-React#1]
https://github.com/keikeka/Simple-Counter-with-React/blob/f33ddef1e3fbb5c41967cec880ccca575639ec49/src/styles/secondscounter.scss#L1

Con que importes en el `index.scss` boostrap ya quedará importado siempre.

**Comment by keikeka** [comment]
Listo, se encuentra actualizado el archivo scss. Sé que las ramas las había creado mal y había trabajado en la master, como me daba error al realizar el push cree una rama development donde hice el push nuevo con la corrección.

**Comment by gaal1le0** [comment]
Perfecto, doy por cerrado el ISSUE.
